### ISSUE TITLE
questions about the dataset

### ISSUE THREAD

**Issue by yongguanjiangshan** [Teoge/DMPR-PS#16]
hi, thank you for your good job. could you tell us what "slots" means in the json file?

**Comment by Teoge** [comment]
It means the "parking-slots", and its first two values are indices of two marking-points.

**Comment by yongguanjiangshan** [comment]
thanks for replying! what does the last two values means? And another quetion, each marks have five values，could you tell us what does the last one value means?

**Comment by Teoge** [comment]
The last two values of a "slots" are the type of the parking-slot and the angle of the parking-slot, which are for the detection of slant parking-slots. And they are not used in DMPR-PS.
The last value of a "marks" is indicates the shape of a marking-point, with `0` represents "T" shape and `1` represents "L" shape.

**Comment by yongguanjiangshan** [comment]
i got it, thank you very much!!!
