### ISSUE TITLE
can‘t display the plot of parking slots on the image

### ISSUE THREAD

**Issue by wannanyang** [Teoge/DMPR-PS#7]
Hello Teoge
Thanks  for your code.
When I took the step of inference,I found that the plot of marking points on the image can display.However,it can‘t display the plot of parking slots on the image.So i write you here for help to slove this problem.

**Comment by Teoge** [comment]
Oh, this is my fault. In order to display the inference results of parking-slots, you need to add argument `--inference_slot` when running `inference.py`. I will modify and add this in `README.md`.

**Comment by wannanyang** [comment]
> Oh, this is my fault. In order to display the inference results of parking-slots, you need to add argument `--inference_slot` when running `inference.py`. I will modify and add this in `README.md`.

**Comment by wannanyang** [comment]
thank you for your answer to solve the problem
